try:
    a = 5
except:
    print("error!")

print(a)
